### ISSUE TITLE
tfo version should print the version without first prompting

### ISSUE THREAD

**Issue by Amanibhavam** [isaaguilar/terraform-operator-cli#10]
`tfo version` should show the version and not prompt to create a config file.  When it creates the config file, it fails because directory `~/.tfo` does not exist.  This is with version `2.0.0-beta2`

```
$ tfo version
Do you want to create '/home/ubuntu/.tfo/config' (Y/n): y
2023/08/19 03:05:17 open /home/ubuntu/.tfo/config: no such file or directory
```

After creating `~/.tfo` the config file creation is successful, version is printed:

```
$ tfo version
Do you want to create '/home/ubuntu/.tfo/config' (Y/n): y
tfo-2.0.0-beta2
```

**Comment by isaaguilar** [comment]
Thanks for finding that, you're right there should be no prompt to create the .tfo dir.

**Comment by isaaguilar** [comment]
Fixed https://github.com/isaaguilar/terraform-operator-cli/commit/6d31a6bdf09d2a060ab9a73f88e28c146aa6e9da#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261
